# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Deividas Stankūnas
title: Casting Director / Photographer / Voice Over Artist
email: deividasstankunas9@gmail.com
phone: +37060886951

# Dark Mode (true/false/never)
darkmode: true

# Social links

facebook_username: erdvis
instagram_username: erdvis


# Additional icon links
additional_links:
- title: Strava
  icon: https://i.pinimg.com/474x/ed/2a/64/ed2a64f9a34b00ad2013bf23cc0dc162.jpg
  url: https://www.strava.com/athletes/16517499
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Deividas, a dedicated and detail-oriented professional with a passion for project management as a casting director. With several years of experience in the entertainment industry, I've honed my skills in identifying and managing talent, overseeing complex projects, and working effectively with cross-functional teams.


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  My passion for cycling has led me to build my own bikes, both for MTB and road cycling. There's something special about building a bike from scratch and then taking it out for a spin, feeling the wind in my face and the freedom of the open road. It's a perfect way to clear my head and get some exercise at the same time. I enjoy both road and off-road cycling, and have competed in a few local events in the past.

 In addition to cycling, I enjoy photography as a way to capture memories and tell stories through images. I'm always learning new techniques and experimenting with different styles to create something truly unique.

 Music production is another hobby that allows me to explore my creative side. I'm currently working on my first album, which is an exciting journey of experimentation and self-expression. There's something magical about creating a piece of music from scratch and watching it come to life. It's a challenging process, but one that's deeply rewarding.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
